# packages in environment at /Users/kaimeng/miniforge3:
#
# Name                    Version                   Build  Channel
abseil-cpp                20210324.2           hc377ac9_0  
absl-py                   0.15.0             pyhd3eb1b0_0  
aiohttp                   3.8.1            py39h1a28f6b_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
anyio                     2.2.0            py39hca03da5_2  
appnope                   0.1.2           py39hca03da5_1001  
argon2-cffi               20.1.0           py39h1a28f6b_2  
astunparse                1.6.3                      py_0  
async-timeout             4.0.1              pyhd3eb1b0_0  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
babel                     2.9.1              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                    openblas  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.4              py39hca03da5_0  
bottleneck                1.3.2            py39heec5a64_1  
brotli                    1.0.7                hc377ac9_0  
brotlipy                  0.7.0           py39h5161555_1003    conda-forge
bzip2                     1.0.8                h620ffc9_4  
c-ares                    1.18.1               h1a28f6b_0  
ca-certificates           2021.10.26           hca03da5_2  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2021.10.8        py39hca03da5_2  
cffi                      1.15.0           py39h52b1de0_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
click                     8.0.3              pyhd3eb1b0_0  
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.11.0           py39hca03da5_0  
conda-package-handling    1.7.3            py39h5161555_1    conda-forge
cryptography              36.0.0           py39hfb8cd70_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0  
dataclasses               0.8                pyh6d0b6a4_7  
debugpy                   1.5.1            py39hc377ac9_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
deprecation               2.1.0              pyhd3eb1b0_0  
entrypoints               0.3              py39hca03da5_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h1192e45_0  
fribidi                   1.0.10               h1a28f6b_0  
frozenlist                1.2.0            py39h1a28f6b_0  
gast                      0.4.0              pyhd3eb1b0_0  
gensim                    4.1.2                    pypi_0    pypi
giflib                    5.2.1                h1a28f6b_0  
google-auth               1.33.0             pyhd3eb1b0_0  
google-auth-oauthlib      0.4.1                      py_2  
google-pasta              0.2.0              pyhd3eb1b0_0  
grpc-cpp                  1.42.0               hedfbb7c_1    conda-forge
grpcio                    1.42.0           py39h95c9599_0  
h5py                      3.6.0            py39h7fe8675_0  
hdf5                      1.12.1               h5aa262f_1  
icu                       69.1                 hbdafb3b_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.8.2            py39hca03da5_0  
importlib_metadata        4.8.2                hd3eb1b0_0  
ipykernel                 6.4.1            py39hca03da5_1  
ipython                   7.31.1           py39hca03da5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
jbig                      2.1                  h1a28f6b_0  
jedi                      0.18.1           py39hca03da5_1  
jinja2                    3.0.2              pyhd3eb1b0_0  
joblib                    1.1.0              pyhd3eb1b0_0  
jpeg                      9e                   h3422bc3_0    conda-forge
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                3.2.0              pyhd3eb1b0_2  
jupyter-packaging         0.11.1             pyhd3eb1b0_0  
jupyter_client            7.1.2              pyhd3eb1b0_0  
jupyter_core              4.9.1            py39hca03da5_0  
jupyter_server            1.6.4            py39h2804cbe_0    conda-forge
jupyterlab                3.2.1              pyhd3eb1b0_1  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.10.3             pyhd3eb1b0_1  
keras                     2.7.0              pyhd8ed1ab_0    conda-forge
keras-preprocessing       1.1.2              pyhd3eb1b0_0  
kiwisolver                1.3.1            py39hc377ac9_0  
krb5                      1.19.2               h3b8d789_0  
lcms2                     2.12                 hba8e193_0  
leptonica                 1.82.0               h27f1f06_0    conda-forge
lerc                      3.0                  hc377ac9_0  
libarchive                3.5.2                hc24d6eb_1    conda-forge
libblas                   3.9.0           11_osxarm64_openblas    conda-forge
libcblas                  3.9.0           11_osxarm64_openblas    conda-forge
libcurl                   7.81.0               h8fe1914_0    conda-forge
libcxx                    12.0.0               hf6beb65_1  
libdeflate                1.8                  h1a28f6b_5  
libedit                   3.1.20210216         h1a28f6b_1  
libev                     4.33                 h1a28f6b_1  
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           11_1_0_h6a59814_26  
libgfortran5              11.1.0              h6a59814_26  
libiconv                  1.16                 h1a28f6b_1  
liblapack                 3.9.0           11_osxarm64_openblas    conda-forge
libnghttp2                1.46.0               h95c9599_0  
libopenblas               0.3.17               hea475bc_1  
libpng                    1.6.37               hb8d0fd4_0  
libprotobuf               3.19.4               hccf11d3_0    conda-forge
libsodium                 1.0.18               h1a28f6b_0  
libssh2                   1.10.0               hb80f160_2    conda-forge
libtiff                   4.3.0                h74060c4_2    conda-forge
libwebp                   1.2.2                h0d20362_0    conda-forge
libwebp-base              1.2.2                h3422bc3_1    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libxml2                   2.9.12               hedbfbf4_1    conda-forge
libzlib                   1.2.11            hee7b306_1013    conda-forge
llvm-openmp               12.0.0               haf9daa7_1  
lz4-c                     1.9.3                hc377ac9_0  
lzo                       2.10                 h1a28f6b_2  
markdown                  3.3.4            py39hca03da5_0  
markupsafe                2.0.1            py39h1a28f6b_0  
matplotlib                3.5.0            py39hca03da5_0  
matplotlib-base           3.5.0            py39h9197a36_0  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mistune                   0.8.4           py39h1a28f6b_1000  
multidict                 5.2.0            py39h1a28f6b_2  
munkres                   1.1.4                      py_0  
nbclassic                 0.2.6              pyhd3eb1b0_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.3.0            py39hca03da5_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  h9aa5885_4    conda-forge
nest-asyncio              1.5.1              pyhd3eb1b0_0  
nltk                      3.6.5              pyhd3eb1b0_0  
notebook                  6.4.6            py39hca03da5_0  
numexpr                   2.8.1            py39h144ceef_0  
numpy                     1.21.2           py39hb38b75b_0  
numpy-base                1.21.2           py39h6269429_0  
oauthlib                  3.1.0                      py_0  
openjpeg                  2.4.0                h062765e_1    conda-forge
openssl                   1.1.1m               h1a28f6b_0  
opt_einsum                3.3.0              pyhd3eb1b0_1  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.3.5            py39h9197a36_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py39hcb29f89_1    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.13.1             pyhd3eb1b0_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
protobuf                  3.19.4           py39hfb83b0d_0    conda-forge
pthread-stubs             0.3                  h1a28f6b_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycosat                   0.6.3           py39h5161555_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd3eb1b0_0  
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.4              pyhd3eb1b0_0  
pyrsistent                0.18.0           py39h1a28f6b_0  
pysocks                   1.7.1            py39h2804cbe_4    conda-forge
python                    3.9.7           h54d631c_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-flatbuffers        2.0                pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0  
pyzmq                     22.3.0           py39hc377ac9_2  
re2                       2021.11.01           hbdafb3b_0    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
regex                     2021.11.2        py39h1a28f6b_0  
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
ruamel_yaml               0.15.80         py39h5161555_1006    conda-forge
scikit-learn              1.0.2            py39h9197a36_1  
scipy                     1.7.3            py39h2f0f56f_0  
seaborn                   0.11.2             pyhd3eb1b0_0  
send2trash                1.8.0              pyhd3eb1b0_1  
setuptools                59.4.0           py39h2804cbe_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smart-open                5.2.1                    pypi_0    pypi
snappy                    1.1.8                hc377ac9_0  
sniffio                   1.2.0            py39hca03da5_1  
sqlite                    3.37.0               h72a2b83_0    conda-forge
tensorboard               2.6.0                      py_1  
tensorboard-data-server   0.6.0            py39hfb8cd70_1    conda-forge
tensorboard-plugin-wit    1.6.0                      py_0  
tensorflow                2.7.0           cpu_py39h2839aeb_0    conda-forge
tensorflow-base           2.7.0           cpu_py39hbdae8f9_0    conda-forge
tensorflow-estimator      2.7.0           cpu_py39h91c69d6_0    conda-forge
termcolor                 1.1.0            py39hca03da5_1  
terminado                 0.13.1           py39hca03da5_0  
tesseract                 5.0.1                ha234a1a_0    conda-forge
testpath                  0.5.0              pyhd3eb1b0_0  
threadpoolctl             2.2.0              pyh0d69192_0  
tk                        8.6.11               he1e0b03_1    conda-forge
tomlkit                   0.9.2              pyhd3eb1b0_0  
tornado                   6.1              py39h1a28f6b_0  
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd3eb1b0_0  
typing-extensions         3.10.0.2             hd3eb1b0_0  
typing_extensions         3.10.0.2           pyh06a4308_0  
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39hca03da5_1  
websocket-client          0.58.0           py39hca03da5_4  
werkzeug                  2.0.2              pyhd3eb1b0_0  
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
wrapt                     1.13.3           py39h1a28f6b_2  
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
yarl                      1.6.3            py39h1a28f6b_1  
zeromq                    4.3.4                hc377ac9_0  
zipp                      3.7.0              pyhd3eb1b0_0  
zlib                      1.2.11            hee7b306_1013    conda-forge
zstd                      1.5.0                h8574219_0  
